# some tmp hex values
# nord-bluegreen: #8fbcbb
# nord-red: #BF616A
# nord-yellow: #EBCB8B
# zenburn-brightyellow: #F0DFAF

add_newline = false

# haven't figured out how to split line while also displaying literal chars '[' and ']' so bit messy
format = '''
[\[]()$username$hostname $directory[\]]()$git_branch$git_status$character'''

[character]
success_symbol = '[\$]()'
error_symbol = '[\$]()'

[username]
style_user = "#F0DFAF"
show_always = true
format = '[$user@]()'

[hostname]
style = "#F0DFAF"
ssh_only = false
format = '[$hostname]()'

[directory]
truncation_length = 1 
format = '[$path]()'

[git_branch]
style = "#F0DFAF"
symbol = ""
format = " [$symbol$branch]($style)"

[git_status]
style = "#BF616A"
format = '([\[$all_status$ahead_behind\]](bold red))'
