add_newline = false

format = '''
[\[](bold cyan)$username$hostname $directory[\]](bold cyan)$git_branch$git_status$character'''

[character]
success_symbol = '[\$](bold cyan)'
error_symbol = '[\$](bold cyan)'

[username]
show_always = true
format = '[$user@](bold cyan)'

[hostname]
ssh_only = false
format = '[$hostname](bold cyan)'

[directory]
truncation_length = 1 
#format = '[\[$path\]]()'
format = '[$path]()'

[git_branch]
symbol = ""
format = "[ $symbol$branch]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
