# some tmp hex values
# nord-bluegreen: #8fbcbb
# nord-red: #BF616A
# nord-yellow: #EBCB8B
# zenburn-brightyellow: #F0DFAF
# gruvbuddy blue: #8abeb7

add_newline = false
command_timeout = 1000
# haven't figured out how to split line while also displaying 
# literal chars '[' and ']' so bit messy
format = '''
[\[](#83a598)$username$hostname $directory[\]](#83a598)$git_branch$git_status$character'''

[character]
success_symbol = '[\$](#83a598)'
error_symbol = '[\$](#83a598)'

[username]
show_always = true
format = '[$user@](#83a598)'

[hostname]
ssh_only = false
format = '[$hostname](#83a598)'

[directory]
truncation_length = 1 
format = '[$path]()'

[git_branch]
symbol = ""
format = " [$symbol$branch](#d3869b)"

[git_status]
format = '([\[$all_status$ahead_behind\]](#E5534F))'
