# some tmp hex values
# nord-bluegreen: #8fbcbb
# nord-red: #BF616A
# nord-yellow: #EBCB8B
# zenburn-brightyellow: #F0DFAF

add_newline = false
command_timeout = 1000
# haven't figured out how to split line while also displaying 
# literal chars '[' and ']' so bit messy
format = '''
[\[](#8abeb7)$username$hostname $directory[\]](#8abeb7)$git_branch$git_status$character'''

[character]
success_symbol = '[\$](#8abeb7)'
error_symbol = '[\$](#8abeb7)'

[username]
# style_user = "#F0DFAF"
show_always = true
format = '[$user@](#8abeb7)'

[hostname]
# style = "#F0DFAF"
ssh_only = false
format = '[$hostname](#8abeb7)'

[directory]
truncation_length = 1 
format = '[$path]()'

[git_branch]
symbol = ""
format = " [$symbol$branch](#b294bb)"

[git_status]
format = '([\[$all_status$ahead_behind\]](#cc6666))'
