# some tmp hex values
# nord-bluegreen: #8fbcbb
# nord-red: #BF616A
# nord-yellow: #EBCB8B
# zenburn-brightyellow: #F0DFAF

add_newline = false
command_timeout = 1000
# haven't figured out how to split line while also displaying 
# literal chars '[' and ']' so bit messy
format = '''
[\[](#F0DFAF)$username$hostname $directory[\]](#F0DFAF)$git_branch$git_status$character'''

[character]
success_symbol = '[\$](#F0DFAF)'
error_symbol = '[\$](#F0DFAF)'

[username]
# style_user = "#F0DFAF"
show_always = true
format = '[$user@](#F0DFAF)'

[hostname]
# style = "#F0DFAF"
ssh_only = false
format = '[$hostname](#F0DFAF)'

[directory]
truncation_length = 1 
format = '[$path]()'

[git_branch]
symbol = ""
format = " [$symbol$branch](#DFAF8F)"

[git_status]
format = '([\[$all_status$ahead_behind\]](bold red))'
